name: Setup RSCLI
description: Setup RSCLI tool for interacting with Reysys services
author: reysys-technology
inputs:
  version:
    description: Version of rscli to install (default is latest)
    required: false
    default: latest
  skip-go-install:
    description: Skip Go installation (set to true if Go is already set up)
    required: false
    default: 'false'
  go-version:
    description: Go version to install (ignored if skip-go-install is true)
    required: false
    default: '1.24'
outputs:
  rscli-version:
    description: The installed version of rscli
    value: ${{ steps.rscli-version.outputs.version }}
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v6
      if: inputs.skip-go-install != 'true'
      with:
        go-version: ${{ inputs.go-version }}
    - uses: actions/github-script@v8
      with:
        script: |
          const version = '${{ inputs.version }}' === 'latest' ? 'latest' : '${{ inputs.version }}';
          await exec.exec('go', ['install', `github.com/reysys-technology/rscli@v${version}`]);
    - id: rscli-version
      uses: actions/github-script@v8
      with:
        script: |
          let version = '';
          await exec.exec('rscli', ['--version'], {
            listeners: {
              stdout: (data) => { version += data.toString(); },
              stderr: (data) => { version += data.toString(); }
            }
          });
          core.setOutput('version', version);
          core.info(`${version}`);
